"use client";

import { motion } from "framer-motion";
import { useState } from "react";
import { SectionWrapper } from "./section-wrapper";

const categories = ["All Products", "Sneakers", "Apparel", "Accessories"];

const products = [
  { name: "Air Max Retro", price: "$189", category: "Sneakers", color: "bg-purple-50" },
  { name: "Urban Hoodie", price: "$89", category: "Apparel", color: "bg-blue-50" },
  { name: "Classic Runner", price: "$149", category: "Sneakers", color: "bg-cyan-50" },
  { name: "Canvas Cap", price: "$39", category: "Accessories", color: "bg-emerald-50" },
  { name: "Street Joggers", price: "$79", category: "Apparel", color: "bg-pink-50" },
  { name: "Leather Belt", price: "$59", category: "Accessories", color: "bg-orange-50" },
];

export function LivePreview() {
  const [activeCategory, setActiveCategory] = useState("All Products");

  const filtered =
    activeCategory === "All Products"
      ? products
      : products.filter((p) => p.category === activeCategory);

  return (
    <SectionWrapper id="live-preview" className="py-32">
      <div className="text-center mb-16">
        <motion.p
          initial={{ opacity: 0, y: 10 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-xs text-purple-600 uppercase tracking-[0.2em] mb-4 font-semibold"
        >
          Live Preview
        </motion.p>
        <motion.h2
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ delay: 0.1 }}
          className="text-3xl sm:text-4xl lg:text-5xl font-bold text-gray-900 tracking-tight mb-5"
        >
          See it in action
        </motion.h2>
        <motion.p
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ delay: 0.2 }}
          className="text-gray-500 max-w-lg mx-auto"
        >
          A real preview of a store generated by Chameleon — fully functional, fully customizable.
        </motion.p>
      </div>

      <motion.div
        initial={{ opacity: 0, y: 30 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        transition={{ delay: 0.2 }}
        className="relative max-w-4xl mx-auto"
      >
        {/* Browser frame */}
        <div className="rounded-2xl border border-gray-200 bg-white overflow-hidden shadow-2xl shadow-gray-200/60">
          {/* Browser chrome */}
          <div className="flex items-center gap-2 px-4 py-3 border-b border-gray-100 bg-gray-50/80">
            <div className="flex gap-1.5">
              <div className="w-3 h-3 rounded-full bg-red-400" />
              <div className="w-3 h-3 rounded-full bg-yellow-400" />
              <div className="w-3 h-3 rounded-full bg-green-400" />
            </div>
            <div className="flex-1 mx-4">
              <div className="h-7 rounded-lg bg-gray-100 flex items-center px-3">
                <span className="text-[11px] text-gray-400 font-mono">https://sneaker-vault.chameleon.dev</span>
              </div>
            </div>
          </div>

          {/* Store header */}
          <div className="px-6 py-4 border-b border-gray-100">
            <div className="flex items-center justify-between">
              <span className="text-gray-900 font-semibold text-sm">SneakerVault</span>
              <div className="flex items-center gap-4 text-xs text-gray-400">
                <span>Shop</span>
                <span>About</span>
                <span>Contact</span>
                <div className="w-5 h-5 rounded-full bg-gray-100 flex items-center justify-center">
                  <svg className="w-3 h-3 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 10.5V6a3.75 3.75 0 10-7.5 0v4.5m11.356-1.993l1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 01-1.12-1.243l1.264-12A1.125 1.125 0 015.513 7.5h12.974c.576 0 1.059.435 1.119 1.007zM8.625 10.5a.375.375 0 11-.75 0 .375.375 0 01.75 0zm7.5 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z" />
                  </svg>
                </div>
              </div>
            </div>
          </div>

          {/* Category tabs */}
          <div className="px-6 pt-5">
            <div className="flex gap-2 flex-wrap">
              {categories.map((cat) => (
                <button
                  key={cat}
                  onClick={() => setActiveCategory(cat)}
                  className={`px-4 py-1.5 rounded-full text-xs font-medium transition-all duration-300 ${
                    activeCategory === cat
                      ? "bg-purple-100 text-purple-700 border border-purple-200"
                      : "bg-gray-50 text-gray-400 border border-transparent hover:text-gray-600"
                  }`}
                >
                  {cat}
                </button>
              ))}
            </div>
          </div>

          {/* Product grid */}
          <div className="p-6 grid grid-cols-2 sm:grid-cols-3 gap-4">
            {filtered.map((product, i) => (
              <motion.div
                key={product.name}
                layout
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.9 }}
                transition={{ delay: i * 0.05, duration: 0.3 }}
                whileHover={{ scale: 1.03 }}
                className="rounded-xl border border-gray-100 overflow-hidden group cursor-pointer hover:shadow-md transition-shadow duration-300"
              >
                <div className={`aspect-square ${product.color} flex items-center justify-center`}>
                  <div className="w-12 h-12 rounded-xl bg-white/60 shadow-sm" />
                </div>
                <div className="p-3 bg-white">
                  <p className="text-xs font-medium text-gray-700">{product.name}</p>
                  <p className="text-xs text-gray-400 mt-0.5">{product.price}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>

        {/* Glow */}
        <div className="absolute -inset-4 bg-gradient-to-r from-purple-100/40 to-blue-100/40 rounded-3xl blur-3xl -z-10" />
      </motion.div>
    </SectionWrapper>
  );
}
