import {
  Theme,
  Store,
  StoreFaq,
  StorePrivacySection,
  StoreShippingReturnsSection,
  StoreTestimonial,
  StoreShippingLocation,
  Category,
  Product,
  ProductImage,
  ProductVariant,
  DomainStatus,
  HeroTextAlign,
  SizeType,
  Unit,
} from "@prisma/client";

export type {
  Theme,
  Store,
  StoreFaq,
  StorePrivacySection,
  StoreShippingReturnsSection,
  StoreTestimonial,
  StoreShippingLocation,
  Category,
  Product,
  ProductImage,
  ProductVariant,
  DomainStatus,
  HeroTextAlign,
  SizeType,
  Unit,
};
